select SUBSTRING('La vas a matar perro', 16,5)
select STR(1234567890)
select STUFF('Wichito es un amor',15,4,'chingon')
select LEN('Wichito es un amor')
select CHAR(65)
select LOWER('WICHITO ES un aMoR')
select UPPER('WICHITO ES un aMoR')
select LTRIM('         WICHITO ES un aMoR')
select RTRIM('WICHITO ES un aMoR         ')
select LTRIM(LOWER('         WICHITO ES un aMoR'))
select RTRIM(UPPER('WICHITO ES un aMoR         ')) 
select RTRIM(UPPER('WICHITO ES un aMoR         ')), LTRIM(LOWER('         WICHITO ES un aMoR'))
select REPLACE('Hola a todos, saludos desde Mexico', 'Mexico','La Joya')
select REVERSE('anita lava la tina')
select PATINDEX('%Mexico%', 'Hola a todos, saludos desde Mexico')
select REPLICATE('Jocy ', 5)